# Generated by Django 4.1.4 on 2023-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_desc', models.TextField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
