# Generated by Django 4.1.4 on 2023-01-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='discount_price',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_title',
            new_name='title',
        ),
    ]
